use std::env;
use std::fs;
use std::path::PathBuf;
use vergen_gitcl::{Emitter, GitclBuilder};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = env::var("OUT_DIR").unwrap();
    let dist_path = PathBuf::from(&manifest_dir).join("../frontend/dist");

    if dist_path.exists() {
        println!("cargo:rerun-if-changed={}", dist_path.display());
    }

    // Generate version.rs with git-based version
    let git_sha = std::process::Command::new("git")
        .args(["rev-parse", "--short=8", "HEAD"])
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_else(|_| "unknown".to_string());

    let git_describe = std::process::Command::new("git")
        .args(["describe", "--tags", "--always"])
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_else(|_| "unknown".to_string());

    // Extract version from tag (strip leading 'v' if present)
    let version = git_describe
        .strip_prefix('v')
        .unwrap_or(&git_describe)
        .split('-')
        .next()
        .unwrap_or(&git_describe)
        .to_string();

    let version_rs = format!(
        r#"// Auto-generated by build.rs - do not edit
pub const VERSION: &str = "{}";
pub const VERSION_FULL: &str = "{}";
pub const GIT_SHA: &str = "{}";
pub const GIT_DESCRIBE: &str = "{}";
"#,
        version, git_describe, git_sha, git_describe
    );

    let version_rs_path = PathBuf::from(&out_dir).join("version.rs");
    fs::write(&version_rs_path, version_rs).expect("Failed to write version.rs");

    println!("cargo:rustc-env=NTD_VERSION={}", version);
    println!("cargo:rustc-env=NTD_VERSION_FULL={}", git_describe);
    println!("cargo:rustc-env=NTD_GIT_SHA={}", git_sha);

    // Set FRONTEND_DIST_PATH for rust-embed
    // In cross builds, the path is mounted at /project/frontend/dist
    // In native builds, it's relative to CARGO_MANIFEST_DIR
    let is_cross = env::var("CROSS_TARGET").is_ok();
    let frontend_dist_path = if is_cross {
        "/project/frontend/dist".to_string()
    } else {
        PathBuf::from(&manifest_dir).join("../frontend/dist")
            .to_string_lossy().into_owned()
    };
    println!("cargo:rustc-env=FRONTEND_DIST_PATH={}", frontend_dist_path);

    // Set cfg flag for cross builds so we use the correct path in lib.rs
    if is_cross {
        println!("cargo:rustc-cfg=cross_build");
    }

    // Note: GIT_DIR environment variable is automatically picked up by vergen
    // when the .git directory is in a non-standard location (e.g., when using
    // cross for Docker-based builds)
    let gitcl = GitclBuilder::default()
        .sha(true)
        .describe(true, true, None)
        .build()
        .expect("Failed to build gitcl config");

    if let Err(e) = Emitter::default()
        .add_instructions(&gitcl)
        .expect("Failed to add vergen instructions")
        .emit()
    {
        println!("cargo:warning=vergen: {}", e);
    }
}
